// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raxrdrzsbnxkddnkdjjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJheHJkcnpzYm54a2RkbmtkamptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTY2MjMsImV4cCI6MjA2MTY5MjYyM30.n5a1J1Wq06d26vYntRfBhyvYvcrvSK-hF6LOij7YbDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);